// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var CS17setup$Reverse = require("./CS17setup.bs.js");

function reverseHelper(_alod, _part) {
  while(true) {
    var part = _part;
    var alod = _alod;
    if (alod) {
      _part = /* :: */[
        alod[0],
        part
      ];
      _alod = alod[1];
      continue ;
    } else {
      return part;
    }
  };
}

function reverse(alod) {
  return reverseHelper(alod, /* [] */0);
}

CS17setup$Reverse.check_expect_list_alpha(/* [] */0, /* [] */0, "empty list");

exports.reverseHelper = reverseHelper;
exports.reverse = reverse;
/*  Not a pure module */
