// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var CS17setup$Reverse = require("./CS17setup.bs.js");

function transpose(mat) {
  if (mat) {
    var match = mat[0];
    if (match) {
      if (match[1]) {
        return /* :: */[
                List.map(List.hd, mat),
                transpose(List.map(List.tl, mat))
              ];
      } else {
        return /* :: */[
                List.flatten(mat),
                /* [] */0
              ];
      }
    } else {
      return Pervasives.failwith("A matrix cannot be 0-dimensional.");
    }
  } else {
    return /* [] */0;
  }
}

CS17setup$Reverse.check_expect_list_list_alpha(transpose(/* :: */[
          /* :: */[
            1,
            /* :: */[
              2,
              /* :: */[
                3,
                /* [] */0
              ]
            ]
          ],
          /* :: */[
            /* :: */[
              4,
              /* :: */[
                5,
                /* :: */[
                  6,
                  /* [] */0
                ]
              ]
            ],
            /* :: */[
              /* :: */[
                7,
                /* :: */[
                  8,
                  /* :: */[
                    9,
                    /* [] */0
                  ]
                ]
              ],
              /* [] */0
            ]
          ]
        ]), /* :: */[
      /* :: */[
        1,
        /* :: */[
          4,
          /* :: */[
            7,
            /* [] */0
          ]
        ]
      ],
      /* :: */[
        /* :: */[
          2,
          /* :: */[
            5,
            /* :: */[
              8,
              /* [] */0
            ]
          ]
        ],
        /* :: */[
          /* :: */[
            3,
            /* :: */[
              6,
              /* :: */[
                9,
                /* [] */0
              ]
            ]
          ],
          /* [] */0
        ]
      ]
    ], "multi element list");

CS17setup$Reverse.check_expect_list_list_alpha(transpose(/* :: */[
          /* :: */[
            1,
            /* :: */[
              2,
              /* [] */0
            ]
          ],
          /* :: */[
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ],
            /* [] */0
          ]
        ]), /* :: */[
      /* :: */[
        1,
        /* :: */[
          3,
          /* [] */0
        ]
      ],
      /* :: */[
        /* :: */[
          2,
          /* :: */[
            4,
            /* [] */0
          ]
        ],
        /* [] */0
      ]
    ], "second multi element list");

exports.transpose = transpose;
/*  Not a pure module */
