// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var CS17setup$Reverse = require("./CS17setup.bs.js");

function vertFlip(mat) {
  return List.map(List.rev, mat);
}

CS17setup$Reverse.check_expect_list_list_alpha(List.map(List.rev, /* :: */[
          /* :: */[
            1,
            /* :: */[
              2,
              /* :: */[
                3,
                /* [] */0
              ]
            ]
          ],
          /* :: */[
            /* :: */[
              4,
              /* :: */[
                5,
                /* :: */[
                  6,
                  /* [] */0
                ]
              ]
            ],
            /* :: */[
              /* :: */[
                7,
                /* :: */[
                  8,
                  /* :: */[
                    9,
                    /* [] */0
                  ]
                ]
              ],
              /* [] */0
            ]
          ]
        ]), /* :: */[
      /* :: */[
        3,
        /* :: */[
          2,
          /* :: */[
            1,
            /* [] */0
          ]
        ]
      ],
      /* :: */[
        /* :: */[
          6,
          /* :: */[
            5,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ],
        /* :: */[
          /* :: */[
            9,
            /* :: */[
              8,
              /* :: */[
                7,
                /* [] */0
              ]
            ]
          ],
          /* [] */0
        ]
      ]
    ], "multi element list");

CS17setup$Reverse.check_expect_list_list_alpha(List.map(List.rev, /* :: */[
          /* :: */[
            1,
            /* :: */[
              2,
              /* [] */0
            ]
          ],
          /* :: */[
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ],
            /* [] */0
          ]
        ]), /* :: */[
      /* :: */[
        2,
        /* :: */[
          1,
          /* [] */0
        ]
      ],
      /* :: */[
        /* :: */[
          4,
          /* :: */[
            3,
            /* [] */0
          ]
        ],
        /* [] */0
      ]
    ], "2X2 multi element list");

CS17setup$Reverse.check_expect_list_list_alpha(List.map(List.rev, /* :: */[
          /* :: */[
            1,
            /* [] */0
          ],
          /* :: */[
            /* :: */[
              3,
              /* [] */0
            ],
            /* [] */0
          ]
        ]), /* :: */[
      /* :: */[
        1,
        /* [] */0
      ],
      /* :: */[
        /* :: */[
          3,
          /* [] */0
        ],
        /* [] */0
      ]
    ], "1X2 multi element list");

exports.vertFlip = vertFlip;
/*  Not a pure module */
